import "./Products.scss";
import Product from "./Product/Product";
import Pdata from "./Pdata";

const Products = ({ innerPage, headingText }) => {
  return (
    <div className="products-container">
      {!innerPage && <div className="sec-heading">{headingText}</div>}
      <div className="products">
        <Product
          id={Pdata[0].id}
          imgsrc={Pdata[0].imgsrc}
          pname={Pdata[0].pname}
          price={Pdata[0].price}
        />
        <Product
          id={Pdata[1].id}
          imgsrc={Pdata[1].imgsrc}
          pname={Pdata[1].pname}
          price={Pdata[1].price}
        />
        <Product
          id={Pdata[2].id}
          imgsrc={Pdata[2].imgsrc}
          pname={Pdata[2].pname}
          price={Pdata[2].price}
        />
        <Product
          id={Pdata[3].id}
          imgsrc={Pdata[3].imgsrc}
          pname={Pdata[3].pname}
          price={Pdata[3].price}
        />
        <Product
          id={Pdata[4].id}
          imgsrc={Pdata[4].imgsrc}
          pname={Pdata[4].pname}
          price={Pdata[4].price}
        />
        <Product
          id={Pdata[5].id}
          imgsrc={Pdata[5].imgsrc}
          pname={Pdata[5].pname}
          price={Pdata[5].price}
        />
        <Product
          id={Pdata[6].id}
          imgsrc={Pdata[6].imgsrc}
          pname={Pdata[6].pname}
          price={Pdata[6].price}
        />
        <Product
          id={Pdata[7].id}
          imgsrc={Pdata[7].imgsrc}
          pname={Pdata[7].pname}
          price={Pdata[7].price}
        />
        <Product
          id={Pdata[8].id}
          imgsrc={Pdata[8].imgsrc}
          pname={Pdata[8].pname}
          price={Pdata[8].price}
        />
        <Product
          id={Pdata[9].id}
          imgsrc={Pdata[9].imgsrc}
          pname={Pdata[9].pname}
          price={Pdata[9].price}
        />
        <Product
          id={Pdata[10].id}
          imgsrc={Pdata[10].imgsrc}
          pname={Pdata[10].pname}
          price={Pdata[10].price}
        />
        <Product
          id={Pdata[11].id}
          imgsrc={Pdata[11].imgsrc}
          pname={Pdata[11].pname}
          price={Pdata[11].price}
        />
        <Product
          id={Pdata[12].id}
          imgsrc={Pdata[12].imgsrc}
          pname={Pdata[12].pname}
          price={Pdata[12].price}
        />
        <Product
          id={Pdata[13].id}
          imgsrc={Pdata[13].imgsrc}
          pname={Pdata[13].pname}
          price={Pdata[13].price}
        />
        <Product
          id={Pdata[14].id}
          imgsrc={Pdata[14].imgsrc}
          pname={Pdata[14].pname}
          price={Pdata[14].price}
        />
        <Product
          id={Pdata[15].id}
          imgsrc={Pdata[15].imgsrc}
          pname={Pdata[15].pname}
          price={Pdata[15].price}
        />
        <Product
          id={Pdata[16].id}
          imgsrc={Pdata[16].imgsrc}
          pname={Pdata[16].pname}
          price={Pdata[16].price}
        />
        <Product
          id={Pdata[17].id}
          imgsrc={Pdata[17].imgsrc}
          pname={Pdata[17].pname}
          price={Pdata[17].price}
        />
        <Product
          id={Pdata[18].id}
          imgsrc={Pdata[18].imgsrc}
          pname={Pdata[18].pname}
          price={Pdata[18].price}
        />
        <Product
          id={Pdata[19].id}
          imgsrc={Pdata[19].imgsrc}
          pname={Pdata[19].pname}
          price={Pdata[19].price}
        />
      </div>
    </div>
  );
};

export default Products;
